import platform

import subprocess
from distutils.command.clean import clean

import numpy
from setuptools import setup, Extension
from setuptools.command.build_ext import build_ext


SOURCES = [
    # _chuck.cpp contains the wrapper created with pybindgen.
    # It is generated by running:
    #   pipenv run python chuck_binding_generator/generate.py
    '_chuck.cpp',
]


# Order is important here, folks
EXTRA_OBJECTS = [
    # This is generated during make by yacc
    'chuck-external/src/core/chuck.tab.o',

    # This is generated during make by lex
    'chuck-external/src/core/chuck.yy.o',

    'chuck-external/src/core/util_math.o',
    'chuck-external/src/core/util_network.o',
    'chuck-external/src/core/util_raw.o',
    'chuck-external/src/core/util_xforms.o',

    'chuck-external/src/host/chuck_main.o',
    'chuck-external/src/host/chuck_audio.o',
    'chuck-external/src/host/chuck_console.o',
    'chuck-external/src/host/RtAudio/RtAudio.o',

    'chuck-external/src/core/chuck.o',
    'chuck-external/src/core/chuck_absyn.o',
    'chuck-external/src/core/chuck_parse.o',
    'chuck-external/src/core/chuck_errmsg.o',
    'chuck-external/src/core/chuck_frame.o',
    'chuck-external/src/core/chuck_symbol.o',
    'chuck-external/src/core/chuck_table.o',
    'chuck-external/src/core/chuck_utils.o',
    'chuck-external/src/core/chuck_vm.o',
    'chuck-external/src/core/chuck_instr.o',
    'chuck-external/src/core/chuck_scan.o',
    'chuck-external/src/core/chuck_type.o',
    'chuck-external/src/core/chuck_emit.o',
    'chuck-external/src/core/chuck_compile.o',
    'chuck-external/src/core/chuck_dl.o',
    'chuck-external/src/core/chuck_oo.o',
    'chuck-external/src/core/chuck_lang.o',
    'chuck-external/src/core/chuck_ugen.o',
    'chuck-external/src/core/chuck_otf.o',
    'chuck-external/src/core/chuck_stats.o',
    'chuck-external/src/core/chuck_shell.o',
    'chuck-external/src/core/chuck_io.o',
    'chuck-external/src/core/chuck_carrier.o',
    'chuck-external/src/core/hidio_sdl.o',
    'chuck-external/src/core/midiio_rtmidi.o',
    'chuck-external/src/core/rtmidi.o',
    'chuck-external/src/core/ugen_osc.o',
    'chuck-external/src/core/ugen_filter.o',
    'chuck-external/src/core/ugen_stk.o',
    'chuck-external/src/core/ugen_xxx.o',
    'chuck-external/src/core/ulib_machine.o',
    'chuck-external/src/core/ulib_math.o',
    'chuck-external/src/core/ulib_std.o',
    'chuck-external/src/core/ulib_opsc.o',
    'chuck-external/src/core/ulib_regex.o',
    'chuck-external/src/core/util_buffers.o',
    'chuck-external/src/core/util_console.o',
    'chuck-external/src/core/util_string.o',
    'chuck-external/src/core/util_thread.o',
    'chuck-external/src/core/util_opsc.o',
    'chuck-external/src/core/util_serial.o',
    'chuck-external/src/core/util_hid.o',
    'chuck-external/src/core/uana_xform.o',
    'chuck-external/src/core/uana_extract.o',

    'chuck-external/src/core/lo/address.o',
    'chuck-external/src/core/lo/blob.o',
    'chuck-external/src/core/lo/bundle.o',
    'chuck-external/src/core/lo/message.o',
    'chuck-external/src/core/lo/method.o',
    'chuck-external/src/core/lo/pattern_match.o',
    'chuck-external/src/core/lo/send.o',
    'chuck-external/src/core/lo/server.o',
    'chuck-external/src/core/lo/server_thread.o',
    'chuck-external/src/core/lo/timetag.o',

    'chuck-external/src/core/util_sndfile.o',
]


INCLUDE_DIRS = [
    '.',
    'chuck-external/src/host/RtAudio',
    'chuck-external/src/host',
    'chuck-external/src',
    'chuck-external/src/core',
    'chuck-external/src/core/lo',
    numpy.get_include(),
]


EXTENSION_CONFIG = dict(
    sources=SOURCES,
    include_dirs=INCLUDE_DIRS,
    extra_objects=EXTRA_OBJECTS,
)


CFLAGS_DARWIN = ['-D__MACOSX_CORE__']


DEBUG = True
if DEBUG:
    CFLAGS_DARWIN += ['-g', '-O0']
    # Build chuck with debug symbols
    import os
    os.environ['CHUCK_DEBUG'] = '1'


LDFLAGS_DARWIN = [
    '-framework', 'CoreAudio',
    '-framework', 'CoreMIDI',
    '-framework', 'CoreFoundation',
    '-framework', 'IOKit',
    '-framework', 'Carbon',
    '-framework', 'AppKit',
    '-framework', 'Foundation',
]


EXTENSION_CONFIG_DARWIN = dict(
    extra_compile_args=CFLAGS_DARWIN,
    extra_link_args=LDFLAGS_DARWIN,
    sources=SOURCES,
    include_dirs=INCLUDE_DIRS,
    extra_objects=EXTRA_OBJECTS,
)


def get_extension_config():
    system = platform.system()
    if system == 'Darwin':
        return EXTENSION_CONFIG_DARWIN
    else:
        return EXTENSION_CONFIG


MAKE_TARGETS = {
    'Darwin': 'osx',
    'Linux': 'linux-alsa',
    'Windows': 'win32',
}


chuck_extension = Extension(
    '_chuck',
    **get_extension_config()
)


class BuildExt(build_ext):
    def run(self, *args, **kwargs):
        cmd = ['make', MAKE_TARGETS[platform.system()]]
        subprocess.check_call(cmd, cwd='chuck-external/src')
        build_ext.run(self, *args, **kwargs)


class Clean(clean):
    def run(self, *args, **kwargs):
        # cmd = ['make', 'clean']
        # subprocess.check_call(cmd, cwd='chuck-external/src')
        clean.run(self, *args, **kwargs)


setup(
    name='chuckpy',
    version='1.0.0',
    description='ChucK bindings for Python',
    author='Elijah Shaw-Rutschman',
    author_email='elijahr+chuckpy@gmail.com',
    packages=['chuckpy'],
    ext_modules=[chuck_extension],
    cmdclass={
        'build_ext': BuildExt,
        'clean': Clean,
    },
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Environment :: Console',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: GNU General Public License v2 (GPLv2)',
        'Operating System :: MacOS :: MacOS X',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 3',
        'Topic :: Multimedia :: Sound/Audio',
        'Topic :: Multimedia :: Sound/Audio :: MIDI',
        'Topic :: Multimedia :: Sound/Audio :: Sound Synthesis',
    ],
)
